### PR TITLE
Reduce logging

### PR DESCRIPTION
**Pull request by crangelsmith**
Reduce logging to epoch level to accelerate run. 

If we want to log at batch level, we can use the debug flag.

### CODE REVIEW

**Review by jolaem — APPROVED** [review]
Does the print actually affect the execution speed?

**Comment by crangelsmith** [comment]
> Does the print actually affect the execution speed?

I think makes it a bit slower because it has to write to disk in the log file. With a very big dataset that is a looot of prints per epoch.

**Comment by jolaem** [comment]
Ok cool, just tested this and it produced a 3 second difference per epoch which with 2000 epochs is well over an hour!

**Comment by crangelsmith** [comment]
I'll merge this now.

**Pull request merged**
