### PR TITLE
Pydantic config

### LINKED ISSUE #201: Consider using pydantic for configuration
https://docs.pydantic.dev/latest/usage/models/

Helps with parameter validation and serialisation.

### PR DESCRIPTION
**Pull request by crangelsmith**
Fixes #201 

- Uses pydantic for input validation
- Moves global variables from config.py to settings.py, leaving config.py for implementation of the point above.
- Added and updated tests.
- Updates in many files for the change of config.VIS_X to settings.VIS_X (X) here is a placeholder.
- Updated config.yml example file to be used in tests.

### CODE REVIEW

**Review by jolaem — APPROVED** [review]
This is great, thanks Camilla!

**Review by marjanfamili — APPROVED** [review]
All good

**Comment by marjanfamili** [comment]
Missing from Readme 

conda install -c conda-forge matplotlib

pip install pyyaml

**Comment by crangelsmith** [comment]
Merging as its been tested locally and Baskerville.

**Pull request merged**
