### PR TITLE
Make a subdirectory for logging

### LINKED ISSUE #80: Make a subdirectory for logging
In the same way as plots and states. 

At the moment the logs are overcrowding the directory and it's hard to find anything.

### PR DESCRIPTION
**Pull request by jolaem**
Prevents overcrowding of the results directory.

Fixes #80

### CODE REVIEW

**Review by marjanfamili — APPROVED** [review]

**Comment by crangelsmith** [comment]
This makes sense, but I wonder if we would we like to create and save all outputs in a new directory ( e.g a time-stamped directory) in each run? This will avoid confusion and overwriting of results. Currently, I'm doing this on an external submission script but maybe we should add it to the main functionality.

**Review by crangelsmith — APPROVED** [review]

**Comment by jolaem** [comment]
@crangelsmith do you mean all outputs as in, including `plots`, `latents`, `logs` etc? Yeah that would be good actually.

**Comment by crangelsmith** [comment]
> @crangelsmith do you mean all outputs as in, including `plots`, `latents`, `logs` etc? Yeah that would be good actually.

Yes, I'm currently doing in a bash script before the run as this:

```
#!/bin/bash
foldername="run_"$(date +%Y%m%d%H%M%S)
mkdir -p "$foldername" 
cd "$foldername" 
python3 /bask/homes/e/eixc0651/camila/affinity-vae/run.py --config_file $1 
```

we could do it this way or in the main code at every run. Also the directory name could have timestamp but also the main config values to make it more understandable: e.g `run_gamma1_beta2_sample1000_timestamp/`.

Let's merge this and create a new issue where we discuss it?

**Comment by jolaem** [comment]
That sounds good. I'd also maybe add `--overwrite` flag that overwrites the most recent one (in case something went wrong like it fell over and you really don't need to keep it).

I'll merge this and make another issue.

**Pull request merged**
